### ISSUE TITLE
Success criterion options

### ISSUE THREAD

**Issue by dunjaseselja** [g4v4g4i/ArgABM#11]
Right now, agents are successful if at the end of the run, there are no fewer agents on the best theory than on another theory. An alternative criterion would be full convergence.

I think there should be an option in the interface for both of these, so that one can select the criterion of success. We could label them as the "monist" success criterion, and the "pluralist" success criterion.

**Comment by daimpi** [comment]
This is currently implemented in the "sucess-criterion-options" branch and can be closed as soon as the branch is merged.
