### ISSUE TITLE
Different calculation of the end of the run?

### ISSUE THREAD

**Issue by dunjaseselja** [g4v4g4i/ArgABM#12]
Conceptual problem: with the current settings for the end of the run, it can happen that many agents become idle: they just stay on the theory which is already mainly red, while some other agents are still working elsewhere. The questions is whether this is counter-intuitive:
On the one hand, this could be understood as agents having moved on to other issues (i.e. each idle agent is interpreted as having exited the field). On the other hand, this could also be understood as the point when we should end the run, since once an agent becomes idle, the main things regarding the domain should be decided.

So the question is whether we should change the end-of-the-run criterion to the one which takes into account the moment in which the first agent has become idle (i.e. as soon as a theory has been fully discovered/explored).

**Comment by daimpi** [comment]
From our 2 Meeting [2016-10-14 Fri 11:48] "Notes for ArgABM":

**Termination criterion**
Christian had some worries about the current model: easy solution would be to slightly adjust the evaluation/strategy step as follows:

- if the current theory is fully red
  - if it is below threshold: immediately jump
  - if it is above the threshold: terminate run
