### ISSUE TITLE
(Optical) problem with radial landscape layout in NetLogo 6

### ISSUE THREAD

**Issue by daimpi** [g4v4g4i/ArgABM#33]
There is a (optical) problem with the radial layout since the conversion of our model to NetLogo 6.0.  The problem is probably due to changes in the way how the `layout-radial` command operates in NetLogo6 ([that's](https://github.com/NetLogo/NetLogo/search?q=radial&type=Code&utf8=%E2%9C%93) what I found in the NetLogo repository). The positioning of arguments was always identical in NetLogo 5.x but seems to be random now. Unfortunately I haven't found a easy solution which would give us back the 5.x behavior. Fortunately though the behavior of our researchers seems not to be affected by the change, the landscape just looks uglier than before.
Nevertheless this is probably something which we want to fix at some point.

**Comment by daimpi** [comment]
Just discovered: strangely when no attacks are present the graph looks just fine. Maybe this has something to do with the overhaul how link reporters work? http://ccl.northwestern.edu/netlogo/docs/transition.html#v60
(just a guess)

**Comment by daimpi** [comment]
The behavior seems to be caused by a bug in NetLogo 6: NetLogo/NetLogo#1301

An easy workaround would be to move the `define-attack-relation-visualize` procedure up within the `define-attack-relation` procedure, particularly to move it before any attack-relations are created (i.e. before `define-attack-relation-create-attacks`). 
On the other hand - considering that the problem is only optical - we could also just wait for the next NetLogo update to fix the problem.

**Comment by g4v4g4i** [comment]
Yes, I think we should wait for NetLogo to fix it.

**Comment by daimpi** [comment]
Fixed with the release of NetLogo 6.0.1: https://ccl.northwestern.edu/netlogo/docs/versions.html
