### ISSUE TITLE
Measurement of communication flow

### ISSUE THREAD

**Issue by daimpi** [g4v4g4i/ArgABM#45]
It would be interesting to have a measurement for the amount of communication flow that happens in our model wrt the different communication structures. I'd propose to collect the following reporters:

1. cumulative communication costs for the run:  the sum of all communication cost that accrued during a run
2. max communication costs paid during the run: amount of communication costs that accrued in the round which had the highest communication costs. Additionally we can record the number of the round where this happened.
3. cumulative unpaid communication costs: this value should usually be zero, and serves more as a check which signals to us that our `max-learn` value is too low for the chosen parameters. (This will not happen with the parametrization we usually test)

(all reporters could be normalized via dividing by the number of ~~groups~~ scientists)

What do you think? :)

**Comment by g4v4g4i** [comment]
Can you elaborate a bit on what the merits would be: what kind of insights could be gained that would help to improve the model or answer interesting research questions? (I don't doubt that you have a good motivation for this: I just think it would be useful for everybody if you elaborate a bit on them.)

**Comment by daimpi** [comment]
Yes certainly :)

Currently we have the rough idea that communication flow increases in the number of scientists and from cycle over wheel to complete. What I'd like to know is how much do this numbers actually differ: Does the complete graph (for x scientists) share twice as much information as the cycle or thrice or…?
In statistical terms what we currently have is an ordinal order, and what we could get is an ratio order [(wiki - the german entry seems more comprehensive though)](https://en.wikipedia.org/wiki/Level_of_measurement#Comparison). 
For models like zollman this is easy as the amount of information flow is directly proportional to the number of links, but in our model this is not necessarily the case as groups might often overlap - especially for large groups - in which landscape they discover .

Regarding the usefulness of this information: I don't have a straightforward use-case for this currently other than curiosity. It could e.g. be that the data reveals significant deviations from the zm baseline described above, which would be quite interesting. But whatever the results it gives us an information on how our communal networks fare in comparison to others like zollman. 

Additionally this metrics would inform us about the impact on the important factor of communication flow, should we choose to augment our model with different communal networks (e.g. random), or different groups (e.g. singleton groups).
